### ISSUE TITLE
Error: Cannot find module 'httpp-forward'

### ISSUE THREAD

**Issue by Dmole** [InstantWebP2P/peer-vnc#15]
```
./bin/osx/node examples/httpp-srv.js 

module.js:340
    throw err;
          ^
Error: Cannot find module 'httpp-forward'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:362:17)
  at require (module.js:378:17)
  at Object.<anonymous> (/Users/me/Downloads/peer-vnc/peer-vnc-pkg-release-osx/examples/httpp-srv.js:8:15)
  at Module._compile (module.js:449:26)
  at Object.Module._extensions..js (module.js:467:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.runMain (module.js:492:10)
  at process.startup.processNextTick.process._tickCallback (node.js:245:9)

```

**Comment by sequoiar** [comment]
try npm install httpp-forward

**Comment by Dmole** [comment]
That would likely work but the point I'm trying to make is that the package should be included in the zip, due to the wording "Install with prebuilt packages, just download and unzip it".
