### ISSUE TITLE
linux64 package crashes

### ISSUE THREAD

**Issue by dhsc19** [InstantWebP2P/peer-vnc#7]
After submitting the password in the noVNC web interface, the status shows "Starting VNC handshake".  At that moment the nodejs instance crashes, showing:

/home/tommy/Downloads/peer-vnc-pkg-release-linux64/novnc.js:53
    		var wss = new WSS(ws);
    		          ^
TypeError: undefined is not a function
    at Socket.<anonymous> (/home/tommy/Downloads/peer-vnc-pkg-release-linux64/novnc.js:53:17)
    at Socket.g (events.js:192:14)
    at Socket.EventEmitter.emit (events.js:93:17)
    at Object.afterConnect [as oncomplete] (net.js:752:10)

**Comment by sequoiar** [comment]
just update linux64 package, try it again

https://github.com/InstantWebP2P/peer-vnc/archive/pkg-release-linux64.zip
